name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.2.4]
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v5
      with:
        version: ${{ matrix.nim }}
    - name: Install dependencies
      run: nimble install -d -y
    - name: Test
      run: nimble test -y
    - name: Build binary
      run: nimble build -y
