name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nim: [2.2.6]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: nimble install -d -y
    - name: Test
      run: nimble test -y
    - name: Build binary
      run: nimble build -y
